### ISSUE TITLE
Glib being used with VS Mac 17.0

### ISSUE THREAD

**Issue by mrward** [mrward/monodevelop-project-system-tools#3]
View container initialization failed
System.DllNotFoundException: Unable to load shared library 'libglib-2.0-0.dll' or one of its dependencies. In order to help diagnose loading problems, consider setting the DYLD_PRINT_LIBRARIES environment variable: dlopen(liblibglib-2.0-0.dll, 1): image not found
   at GLib.Marshaller.g_utf16_to_utf8(Char* native_str, IntPtr len, IntPtr items_read, IntPtr& items_written, IntPtr& error)
   at GLib.Marshaller.StringToPtrGStrdup(String str, IntPtr& len)
   at GLib.Markup.EscapeText(String s)
   at MonoDevelop.ProjectSystem.Tools.Gui.BinaryLogBuildTreeView.GetTreeNodeText(NodeViewModel nodeViewModel)
   at MonoDevelop.ProjectSystem.Tools.Gui.BinaryLogBuildTreeView.SetTreeNodeValues(TreeNavigator navigator, BaseViewModel viewModel)
   at MonoDevelop.ProjectSystem.Tools.Gui.BinaryLogBuildTreeView.AddTreeViewItems()
   at MonoDevelop.ProjectSystem.Tools.Gui.BinaryLogBuildTreeView..ctor(ObservableCollection`1 rootViewModels)
   at MonoDevelop.ProjectSystem.Tools.Gui.BinaryLogDocumentControllerExtension.OnInitializeView()
   at MonoDevelop.Ide.Gui.Documents.DocumentController.GetDocumentView()

**Comment by mrward** [comment]
Fixed in https://github.com/mrward/monodevelop-project-system-tools/commit/a73cc7ec569659665c73807a6a01edec52b2bb60
